Fix ShapeCustom_SweptToElementary to use new std::optional API for Geom_Surface::D0
Updated three D0 calls to unwrap std::optional returns:

1. SR->D0(U1, V1, P0) on Geom_SurfaceOfRevolution
2. SPH->D0(US1, VS1, PS) on Geom_SphericalSurface
3. SR->D0(UR1, VR1, PR) on Geom_SurfaceOfRevolution

All changed to:
  if (auto aResult = surface->D0(U, V))
    point = *aResult;

This fixes compilation errors:
  error: too many arguments to function call, expected 2, have 3